AllowDelete now needs true instead of 'Yes'
Microsoft have changed the pac --allowDelete to true, instead of false, without this fix the follwing error is given:

```
Microsoft PowerPlatform CLI
Version: 1.13.4+g79187cf

Error: The value passed to --allowDelete is not valid. If no value is passed, the argument will default to true. Values: true, false.

Usage: pac solution pack --zipfile [--folder] [--packagetype] [--log] [--errorlevel] [--singleComponent] [--allowDelete] [--allowWrite] [--clobber] [--map] [--sourceLoc] [--localize] [--useLcid] [--useUnmanagedFileForMissingManaged] [--disablePluginRemap]
```